name: Test Pytorch3d

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install pytorch3d
      run: |
        pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html

    - name: Check versions
      run: |
        python --version
        python -c "import torch; print(torch.__version__)"
        python -c "import pytorch3d; print(pytorch3d.__version__)"
