name: Test Pytorch3d

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pytorch3d
      run: |
        conda install pytorch=2.2.0 torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
        conda install -c fvcore -c iopath -c conda-forge fvcore iopath
        