name: Test Pytorch3d with Conda

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'
        activate-environment: myenv
        auto-activate-base: false

    - name: Install dependencies
      run: |
        conda install pytorch=2.1.2 torchvision cpuonly  -c pytorch -y
        conda install -c fvcore -c iopath -c conda-forge fvcore iopath

    - name: Install Pytorch3d
      run: |
        conda install pytorch3d -c pytorch3d
        
    - name: Check versions
      run: |
        python -c "import pytorch3d; print(pytorch3d.__version__)"
